spring:
  application.name: physician-assistant-service
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://34.28.172.140:3306/physician_db_prod
    username: physician-service-user
    password: ENSF@607
    driver-class-name: com.mysql.cj.jdbc.Driver
